version: "3.8"

services:
  mariadb:
    image: wodby/mariadb:10.4-3.8.5
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DRUPAL_DATABASE_NAME}"
      MYSQL_USER: "${DRUPAL_DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DRUPAL_DATABASE_PASSWORD}"

  php:
    image: wodby/drupal-php:7.3-dev-4.17.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DRUPAL_DATABASE_HOST: "${DRUPAL_DATABASE_HOST}"
      DRUPAL_DATABASE_PORT: "${DRUPAL_DATABASE_PORT}"
      DRUPAL_DATABASE_USERNAME: "${DRUPAL_DATABASE_USERNAME}"
      DRUPAL_DATABASE_PASSWORD: "${DRUPAL_DATABASE_PASSWORD}"
      DRUPAL_DATABASE_NAME: "${DRUPAL_DATABASE_NAME}"
      DRUPAL_HASH_SALT: "${DRUPAL_HASH_SALT}"
      WODBY_ENVIRONMENT_NAME: "${PROJECT_NAME}-local"
      DRUSH_BASE_URI: "${PROJECT_BASE_URL}:8000"
    ## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    #      PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/nginx:1.19-5.10.0
    depends_on:
      - php
    environment:
      NGINX_FASTCGI_INTERCEPT_ERRORS: "off"
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal8
    #      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

