<?php

/**
 * @file
 * Hooks and such for training_customization.
 */

use Drupal\Core\Language\LanguageInterface;

/**
 * Processes a language select list form element.
 *
 * @param array $element
 *   The form element to process.
 *
 * @return array
 *   The processed form element.
 */
function _training_customization_process_language_select($element) {
  unset(
    $element['#options'][LanguageInterface::LANGCODE_NOT_SPECIFIED],
    $element['#options'][LanguageInterface::LANGCODE_NOT_APPLICABLE]
  );
  return $element;
}

/**
 * Implements hook_element_info_alter().
 */
function training_customization_element_info_alter(array &$type) {
  // Alter the language_select element so that it will be rendered like a select
  // field.
  if (isset($type['language_select'])) {
    $type['language_select']['#process'][] = '_training_customization_process_language_select';
  }
}
